# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GRASSGISColorTableImportDockWidget
                                 A QGIS plugin
 Module for loading and applying GRASS color table files to raster data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-04-14
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Josef Jehlička
        email                : jehlijos@cvut.cz
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal, Qt
from qgis.utils import iface
from qgis.gui import QgsMessageBar
from qgis.core import Qgis

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'GRASS_GIS_Color_Table_Import_dockwidget_base.ui'))


class GRASSGISColorTableImportDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(GRASSGISColorTableImportDockWidget, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.RunButton.clicked.connect(self.Run)


    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()

    def Run(self):
        # Get the selected layer from SelectLayerComboBox
        selected_file = self.SelectLayerComboBox.currentText()

        # Add warning if no layer is selected
        if selected_file == "":
            iface.messageBar().pushMessage(
                "Error",
                "Please select a raster layer!",
                level = Qgis.Warning,
                duration = 5
            )
            return

        # Get the input GRASS color table file
        GRASStable = self.SelectFileWidget.filePath()

        # Add warning if no file is selected
        if GRASStable == "":
            iface.messageBar().pushMessage(
                "Error",
                "Please select a GRASS color table!",
                level = Qgis.Warning,
                duration = 5
            )
            return
